name: make website

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

jobs:

  deploy_mkdocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: |
            pip install mkdocs
            mkdocs gh-deploy --force
